### ISSUE TITLE
Error when signing psbt when running mpc-core-kit/tkey-mpc-react-bitcoin-example

### ISSUE THREAD

**Issue by d-smith** [Web3Auth/web3auth-core-kit-examples#148]
### **Describe the bug**

When attempting to sign a psbt using the tkey-mpc-react-bitcoin-example app I encounter the following error:

```
psbtutils.js:63 Uncaught (in promise) TypeError: pubkey.slice is not a function
    at pubkeyPositionInScript (psbtutils.js:63:1)
    at pubkeyInScript (psbtutils.js:77:1)
    at checkScriptForPubkey (psbt.js:1060:1)
    at getHashAndSighashType (psbt.js:1192:1)
    at Psbt._signInputAsync (psbt.js:757:1)
    at psbt.js:733:1
    at async sendTransaction (App.tsx:613:1)
```

Console output prior to the error

```
TSS Public Key:  Point {x: BN, y: BN} With Factors/Shares: {043ab793607f67d0046658ccd4b5fd5142571e448ff84658605706cd7f0fc7ad2f82d9d881625ec1dfbebd4191b0a158b5a1f85b1544c95bb5d06929866e80bcf7: Array(1)}
App.tsx:593 txHex 02000000018f2f4fc8ed92612a76f96b183d57b11fe77591a33a711b5fde234d61a02effbc000000006a473044022007448ef6f9adc139aa58017e4159ec6e079774eb3f6f43122c166a2408eda22f02205305d6626b82d1d3cb212d30050eb589a60441fdcbcc914770f927242b696bbb01210307124bd436c357276745b784074d0e2a704668f4c109df2bad3ccca98fc2f208fdffffff02be8c1500000000001976a914c641d2f40c686c3eabf77f49a58b9703ee5c3aa388acf9462a7f000000001976a914691f7a8aa71ed7f6ca9ab4f17be9bb1472a09cce88acdb412500
App.tsx:28 Bitcoin address mybEwa3zXJEquC1F1rLY18i2r6ytn5k8T2
App.tsx:596 mybEwa3zXJEquC1F1rLY18i2r6ytn5k8T2 string
App.tsx:28 Signing transaction...
```

### **To Reproduce**

1. Login using the localhost variation
2. Play around a little bit, looking at the login response, etc
3. Get the bitcoin address, fund it, wait for the funding to be confirm
4. Grab the UTXID from blockstream.
5. Press the sign psbt button

### **Device Info (please complete the following information):**

- Device: laptop computer
- OS:  Ubuntu 20.04.6 LTS
- Browser: chrome
- Web3Auth Version [e.g. 1.0.0]

### **Additional context**

Login response

```
[
{
"userInfo": {
"verifierId": "50298@example.com",
"verifier": "torus-test-health"
},
"signatures": [
"{\"data\":\"eyJleHAiOjE2ODkzNTY0OTYsInRlbXBfa2V5X3giOiJjYmIxOTExYTlmMTQ4YWE5YWEwNzliYzM1ZmYxMDMxODBlY2M0OGNhYmVmYWUzYTNkMmU4MmExODFjNjU0M2FlIiwidGVtcF9rZXlfeSI6IjRhNjJiOWNkY2M0MzQ2Y2ZiNjEyMGY5NGNjYzgyOGUxNjc1OWQyOGExODExNmJiZjU0YmZiYTc2ZDUxODE4NDQiLCJ2ZXJpZmllcl9uYW1lIjoidG9ydXMtdGVzdC1oZWFsdGgiLCJ2ZXJpZmllcl9pZCI6IjUwMjk4QGV4YW1wbGUuY29tIiwic2NvcGUiOiIifQ==\",\"sig\":\"e838e2edbed17bc3f94d16b19c880bde4a992f676db95d759e72f4f2b4734db7064d327eab4ee53af22b5894cc5bdefb61bcfc34be030db5913de06c08e5931d1c\"}",
"{\"data\":\"eyJleHAiOjE2ODkzNTY0OTUsInRlbXBfa2V5X3giOiJjYmIxOTExYTlmMTQ4YWE5YWEwNzliYzM1ZmYxMDMxODBlY2M0OGNhYmVmYWUzYTNkMmU4MmExODFjNjU0M2FlIiwidGVtcF9rZXlfeSI6IjRhNjJiOWNkY2M0MzQ2Y2ZiNjEyMGY5NGNjYzgyOGUxNjc1OWQyOGExODExNmJiZjU0YmZiYTc2ZDUxODE4NDQiLCJ2ZXJpZmllcl9uYW1lIjoidG9ydXMtdGVzdC1oZWFsdGgiLCJ2ZXJpZmllcl9pZCI6IjUwMjk4QGV4YW1wbGUuY29tIiwic2NvcGUiOiIifQ==\",\"sig\":\"0f0f130683dfa936602d95788d2095929226eb6b66ab36296b053e583153cecc237dfbb0e096e7efda197391bf2f55e8b37e1f78ba6891e77ca22da1d04aa6041c\"}",
"{\"data\":\"eyJleHAiOjE2ODkzNTY0OTYsInRlbXBfa2V5X3giOiJjYmIxOTExYTlmMTQ4YWE5YWEwNzliYzM1ZmYxMDMxODBlY2M0OGNhYmVmYWUzYTNkMmU4MmExODFjNjU0M2FlIiwidGVtcF9rZXlfeSI6IjRhNjJiOWNkY2M0MzQ2Y2ZiNjEyMGY5NGNjYzgyOGUxNjc1OWQyOGExODExNmJiZjU0YmZiYTc2ZDUxODE4NDQiLCJ2ZXJpZmllcl9uYW1lIjoidG9ydXMtdGVzdC1oZWFsdGgiLCJ2ZXJpZmllcl9pZCI6IjUwMjk4QGV4YW1wbGUuY29tIiwic2NvcGUiOiIifQ==\",\"sig\":\"ca11b69f58534e82061b347bab9f4ac2779ebd50ef93aecd4ef2dbc415f4f23157b8c8d207667428733276003e9ed6906b98cf78b12f69618f49baaa719af7741b\"}",
"{\"data\":\"eyJleHAiOjE2ODkzNTY0OTYsInRlbXBfa2V5X3giOiJjYmIxOTExYTlmMTQ4YWE5YWEwNzliYzM1ZmYxMDMxODBlY2M0OGNhYmVmYWUzYTNkMmU4MmExODFjNjU0M2FlIiwidGVtcF9rZXlfeSI6IjRhNjJiOWNkY2M0MzQ2Y2ZiNjEyMGY5NGNjYzgyOGUxNjc1OWQyOGExODExNmJiZjU0YmZiYTc2ZDUxODE4NDQiLCJ2ZXJpZmllcl9uYW1lIjoidG9ydXMtdGVzdC1oZWFsdGgiLCJ2ZXJpZmllcl9pZCI6IjUwMjk4QGV4YW1wbGUuY29tIiwic2NvcGUiOiIifQ==\",\"sig\":\"ed45f6335f485f746042f12b6e90bd3ea818d388421738ba3f960246815f71d86e2df3ef66af5b499f03bab1057122596e1912064fb87599ad8fe47c7f4fafc81c\"}"
],
"privateKey": "7a2dd7952f4663850a3ba60fd0f04cb6618518ebd7cb5496232d7d93299770a5"
}
]
```

**Comment by yashovardhan** [comment]
Please ask your questions on https://community.web3auth.io/
